nefit:
  serial_number: [serialnumber]
  access_key: [access_key]
  password: [password]
  reconnect_timeout: 30
  timezone: 1
  conversion_factor_m3: 0.102365

file:
  path: /var/nefit-easy/status.json

influxdb2:
  url: http://localhost:8086
  token: [token]
  organization: [my-org]
  bucket: iot_metrics

mqtt:
  url: mqtt://localhost:1883
  credentials:
    username: [mqtt-username]
    password: [mqtt-password]
  base_topic: nefit/[serialnumber]
  publish: both # values: json, fields, both
  last_will:
    topic: nefit/[serialNumber]/activation
    payload:
      online: online
      offline: offline
  command: true

debug: nefit-easy-core nefit-easy-connector-service:*
polling_interval: 10
